apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: frontend1
spec: 
  selector:
    matchLabels: 
      app: frontend1 
  template:
    metadata:
      labels: 
        app: frontend1
    spec:
      containers: 
      - name: frontend1
        image: melvinsamuel070/frontend1:1
        ports: 
        - containerPort: 3000

      
