name: Deployment of Application Rev
on:
    push:
        branches: 
        - master

jobs: 
    DeploymentApp:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout from workflows"
          uses: actions/checkout@v4
        
        - name: "Build the Docker image"
          run: |
            docker pull melvinsamuel070/frontend1:1
        
        - name: "LOgin to Docker"
          run: |
            docker login -u melvinsamuel070 -p ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: "Set the token"
          run: |
            echo ${{ secrets.GITHUB_TOKEN }}

        - name: "Push the Docker image to the Hub"
          run: |
            docker push melvinsamuel070/frontend1:1 
       
        - name: "Go to the repo for Helm"
          run: |

            git config --global user.email "melvinsamuel070@gmail.com"
            git config --global user.name "melvinsamuel070"
            git clone https://github.com/melvinsamuel070/rev_app_helm.git rev_app_helm
            cd rev_app_helm 
            cd rev-app-chart/templates
            sed -i 's/frontend1:1/frontend1:2/' deployment.yaml
            # sed -i 's/rev_app:1/rev_app:2/' service.yaml
            cat deployment.yaml
            # cat service.yaml
            git status
            git add .
            git commit -m "Updated helm"
            # git remote set-url melvin https://${{ secrets.GITHUB_TOKEN }}@github.com/melvinsamuel070/rev_app_helm.git
            git push melvin master
            
